apiVersion: v1
kind: Service
metadata:
  name: ftgo-consumer-service
spec:
  selector:
    app: ftgo-consumer-service
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-consumer-service
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ftgo-consumer-service
  template:
    metadata:
      labels:
        app: ftgo-consumer-service
    spec:
      containers:
        - name: ftgo-consumer-service
          image: gressier/ftgo-consumer-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes,development
          ports:
            - name: http
              containerPort: 80
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            failureThreshold: 12
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]