spring:
  application:
    name: ftgo-consumer-service
  profiles:
    active: local,development
  jackson:
    default-property-inclusion: non_null

--- # Local
spring:
  config:
    activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ftgo_consumer_service
server:
  port: 8081
logging:
  exception-conversion-word: '%rootException'

--- # Development
spring:
  config:
    activate.on-profile: development
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    username: ftgo_consumer_service
    password: ftgo_consumer_service
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    dev.foodtogo: debug
    org.hibernate.SQL: debug
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web.exposure.include: '*'

--- # Production
spring:
  config:
    activate.on-profile: production
  datasource:
    username: ftgo_consumer_service
    password: CHANGE_ME
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate